from __future__ import annotations

from html import escape
from pathlib import Path

from agent_common.models import RunContext


def run(arguments: dict[str, object], context: RunContext) -> dict[str, object]:
    output_path = Path(str(arguments['output_path'])).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    title = str(arguments.get('title', 'Generated Page'))
    headline = str(arguments.get('headline', title))
    prompt = str(arguments.get('prompt', ''))
    footer = str(arguments.get('footer', f'run: {context.run_id}'))
    sections = arguments.get('sections', [])
    if not isinstance(sections, list) or not sections:
        sections = [prompt or 'Generated by html_page_builder']
    html_sections = ''.join(
        f"<section><p>{escape(str(section))}</p></section>" for section in sections
    )
    html = f"""<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
    <title>{escape(title)}</title>
    <style>
      :root {{ color-scheme: light; font-family: 'Segoe UI', sans-serif; }}
      body {{ margin: 0; background: linear-gradient(135deg, #f4f0e8, #d9e8f5); color: #12212f; }}
      main {{ max-width: 900px; margin: 0 auto; padding: 64px 24px; }}
      article {{ background: rgba(255,255,255,0.88); border: 1px solid rgba(18,33,47,0.12); border-radius: 24px; padding: 32px; box-shadow: 0 18px 45px rgba(18,33,47,0.12); }}
      h1 {{ margin-top: 0; font-size: 2.6rem; }}
      p {{ line-height: 1.7; }}
      section + section {{ margin-top: 18px; }}
      footer {{ margin-top: 24px; color: #496173; font-size: 0.95rem; }}
      .meta {{ display: inline-block; margin-bottom: 16px; padding: 6px 10px; border-radius: 999px; background: #12212f; color: white; font-size: 0.85rem; }}
    </style>
  </head>
  <body>
    <main>
      <article>
        <div class=\"meta\">easy-agent html_page_builder</div>
        <h1>{escape(headline)}</h1>
        <p>{escape(prompt)}</p>
        {html_sections}
        <footer>{escape(footer)}</footer>
      </article>
    </main>
  </body>
</html>
"""
    output_path.write_text(html, encoding='utf-8')
    return {
        'output_path': str(output_path),
        'title': title,
        'headline': headline,
        'section_count': len(sections),
        'run_id': context.run_id,
    }

